# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  - group: variables1
  - name: ubuntu-latest

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ${vm}
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'arjitks77/azure'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

    - task: aquasecScanner@4
      inputs:
        image: 'azure:93'
        scanType: 'local'
        register: false
        hideBase: false
        showNegligible: false
        windowsScannerVersion: '6.5.0'
        registry: 'arjitks77/azure'
        connection: 'aqua'
